### ISSUE TITLE
Plans for more functionality

### ISSUE THREAD

**Issue by hgleaves-ncuadmin** [Brightspace/valence-sdk-dotnet#6]
Are there any plans for adding more to this skeletal SDK?

I was hoping to see support for a range of Valence REST operations but I see very little here. Ideally we'd be able to use .Net classes and methods to a host of operations like enroll users into orgunits or sections, add sections to ourgunits etc etc.

Most of the code I see appears to be just the authentication with the Valence server but I see no examples of an actual API operation.

I'm expecting (but could be wrong here) that we'd see C# methods (wrappers) for many of the REST operations.

Any info or guidance is much appreciated.

**Comment by j3parker** [comment]
Hey Hugh,

You're correct that the SDK as it exists today is only intended to help clients with the SSO-flow (user login/token exchange) and authenticating individual API calls with Valence's "legacy" signature scheme. At this time we don't have any plans to support high-level API-specific bindings in our SDKs.

Note that the SDKs do not handle our OAuth 2.0 support; we expect clients to use a "standard" OAuth 2.0 client library to integrate with Brightspace.
