### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by Korporal** [Brightspace/valence-sdk-dotnet#7]
Hi,

I'm interested in creating a .Net class library for us to encapsulate access to Valence. We've been leveraging Valence more and more heavily recently and we want to simplify and consolidate this stuff. Much of our Valence processing is non-interactive, not operations performed by this or that user, but rather data manipulations (sections, audits etc) performed as part of specific processing tasks.

Can you explain how we can use this SDK to create a simple Console app that establishes a connection to Vakence (we have app-id, keys etc for our test server) and authenticates a user (presumably) so we can then begin to invoke Valence operations? (e.g. adding sections to org units, setting up audits etc etc).

(We already have a basic service here that we developed, that interfaces for us, but we'd much prefer a generic access library that's not forced to run in a local web service).

The CreateUserContext operation seems to require a callback URL, as if access to valence can only be made from a web server/service - we want generic access from non-web apps (e.g. a console app in our test). But I assume we can leverage OAuth 2's _client_credentials_ grant type to gain access? Do you have any sample code that implements this?

Thx

**Comment by j3parker** [comment]
Valence auth (handled by this library) is similar to OAuth 1.0 (not OAuth 2.0.)

For non-interactive workflows you can acquire user tokens manually (e.g. via the API test tool) and pass them to this function: https://github.com/Brightspace/valence-sdk-dotnet/blob/master/lib/D2L.Extensibility.AuthSdk/ID2LAppContext.cs#L34 (store them in some sensibly safe way; that's up to you to figure out.)

This sample is a CLI tool that, when it starts, opens up a web-browser with a callback URL to a port that the CLI tool is listening on. The user enters their credentials and the token is sent to the CLI tool. It's still interactive but it's a CLI tool: https://github.com/Brightspace/sample-valence-client-side

Our OAuth 2.0 support doesn't include `client_credentials` (intentionally) only `authorization_code` (and we could support `implicit` in the future but don't have plans.) For backend things internally we use this form of OAuth 2.0: https://developers.google.com/identity/protocols/OAuth2ServiceAccount It's slightly more complicated though and we don't expose it externally at this time.
